use_frameworks!

target 'ANActionSheet_Example' do
  pod 'ANActionSheet', :path => '../'

  target 'ANActionSheet_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
